### PR TITLE
doc: add modern build

### LINKED ISSUE #967: Document modern mode
### What problem does this feature solve?

https://github.com/nuxt/nuxt.js/pull/4231

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c141">#c141</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by clarkdo**
Resolve #967

### CODE REVIEW

**Comment by manniL** [comment]
@clarkdo I've added a few word changes.

One question left:

Can you set `modern` to `true` and Nuxt will use client/server depending on the mode (SSR/SPA/generated)? If so, we should add that to the docs!

**Comment by clarkdo** [comment]
For now， true equals server

**Comment by manniL** [comment]
Alright. It might be useful to add that "auto-detection" so people only would have to use `modern: true` (but still could use `modern: client` in universal mode if they want to)

**Comment by clarkdo** [comment]
@manniL Will add the detection feature in next release

**Comment by Koc** [comment]
@clarkdo can you also describe how to configure modern build with http2 push headers (`pushAssets`)?

**Comment by clarkdo** [comment]
@Koc 
For `server` modern mode, it's same as normal mode, you can refer https://nuxtjs.org/api/configuration-render#http2

For `client` modern mode, I'll open a pr for it and will also be same as normal mode in next release 😸

**Pull request merged**
