### PR TITLE
en: deploy to AWS Lambda function.md

### PR DESCRIPTION
**Pull request by tomasSlouka**
I was searching for a practical guide on how to deploy an SSR Nuxtjs app to AWS lambda but I was not able to find anything working on the internet. Maybe this will help someone who wants to use AWS Lambda.

Thanks

### CODE REVIEW

**Comment by manniL** [comment]
Does the original author allows publishing this in the nuxt docs?

**Comment by tomasSlouka** [comment]
It is a slightly modified version and the original author has it publicly accessible on his GitHub repo under the MIT license. Otherwise, I did not ask for permission. The .md file I commit was written by me.

**Comment by manniL** [comment]
Thanks for the info!

WDYT @Atinux ?

**Comment by Atinux** [comment]
cc @aldarund

**Comment by manniL** [comment]
As discussed in the discord, I don't feel very comfortable to link to a repository outside nuxt-community in the docs.

**Comment by tomasSlouka** [comment]
very well ... no problem guys .. thx for your time with this pull request ;) I am closing it.

**Pull request closed without merging**
