### PR TITLE
Add Hooks documentation

### PR DESCRIPTION
**Pull request by husayt**
Add documentation for hooks. @pi0 @Atinux hooks haven't been documented so far. So I made a first attempt. But I need you guys to review. There is not much about hooks anywhere, they are least known part of nuxt. It will be good to give them good coverage. I went though source code and listed all the hooks I could find in the code. It will be good to add description for some of them I was not sure what they do.

Thanks

### CODE REVIEW

**Comment by Atinux** [comment]
Hi @husayt 

Thank you so much for this, I added some descriptions, will keep add them the next days!

You rock!

**Comment by husayt** [comment]
@Atinux in examples i guess it is better to `nuxt...` than `this.nuxt...`

**Comment by Atinux** [comment]
Yes it would be better, except for Modules section @husayt

**Comment by husayt** [comment]
@Atinux I think what we have is good for now. Lets push it and continue enhancing

**Pull request merged**
