### PR TITLE
API for the contribution page (for translators like that)

### PR DESCRIPTION
**Pull request by inouetakuya**
This is the API for [Contribution page (for translators like that) by inouetakuya · Pull Request #130 · nuxt/nuxtjs.org](https://github.com/nuxt/nuxtjs.org/pull/130)

### CODE REVIEW

**Comment by pi0** [comment]
Really nice idea! BTW isn't anyway to get this data (maybe per .md file) from GitHub API?

**Comment by inouetakuya** [comment]
Your idea sounds good! I will try it! :muscle:

**Comment by Atinux** [comment]
cc @alexchopin 

We plan to add something like this to the new doc @inouetakuya 

It will be directly integrated from GitHub commits & CMTY (https://nuxtjs.cmty.io/members)

**Comment by inouetakuya** [comment]
@Atinux

> We plan to add something like this to the new doc
> It will be directly integrated from GitHub commits & CMTY (https://nuxtjs.cmty.io/members)

Sounds good!! :smile:

I have scratched my idea.

* https://github.com/nuxt/nuxtjs.org/pull/130#issuecomment-385584035

image

I hope it is of some help.

I will close this pull request because it is no longer needed.

**Pull request closed without merging**
