### PR TITLE
the file import url is not right

### PR DESCRIPTION
**Pull request by fillfive**
`import axios from '~plugins/axios'` 改为 `import axios from '~/plugins/axios'`

### CODE REVIEW

**Comment by manniL** [comment]
Both works :relaxed:

**Comment by fillfive** [comment]
image
image
it error when I use this.

**Comment by fillfive** [comment]
@manniL

**Comment by manniL** [comment]
Interesting. This *should* work AFAIK.

Thanks for the info.

**Comment by fillfive** [comment]
Thank you. the nuxt docs help me a lot. Thanks for your efforts.

**Comment by manniL** [comment]
That's great to hear! Appreciate the feedback :relaxed: 

Thanks for your contribution mate :pray:

**Pull request merged**
