### PR TITLE
srb: Translate Nuxt.js

### PR DESCRIPTION
**Pull request by TesalVector**
Hello guys!

I was add first four files for translate **Nuxt.js docs** on Serbia language! :)
Soon I will add other files.

### CODE REVIEW

**Comment by TesalVector** [comment]
Why not working pull request!
I just add files for translate Buxt.js docs!

**Comment by manniL** [comment]
@TesalVector Ignore the failing `now` check ;)

**Comment by TesalVector** [comment]
Hey man! :)
Have I done it successfully pull request or I was not?

**Comment by manniL** [comment]
@TesalVector Everything is alright! ☺️ Keep on going 👍

**Comment by TesalVector** [comment]
@manniL 
Coool man! :smiley:
Now I received your e-mail (gmail). Thank you for your quick response and support! :smile:

**Comment by debs-obrien** [comment]
Thanks for your contributions. We are now closing this repo as docs have now moved to nuxtjs.org using content module. Please continue your contributions on that site especially focusing on the guides folder which is the new docs. Thanks

https://github.com/nuxt/nuxtjs.org/blob/master/README.md

**Pull request closed without merging**
