### PR TITLE
[Docs FR]: French version ready for starting online life.

### PR DESCRIPTION
**Pull request by Haeresis**
Hi @Atinux!

This PR contains all french content ready to be online.

Currently, the part translated are :

— guide

the part not translated but with a message indicate pages is under translation is :

- api
- examples
- faq

The message is :

```HTML
<p style="width: 294px;position: fixed; top : 64px; right: 4px;" class="Alert Alert--orange"><strong>⚠Cette page est actuellement en cours de traduction française. Vous pouvez repasser plus tard ou <a href="https://github.com/vuejs-fr/nuxt" target="_blank">participer à la traduction</a> de celle-ci dès maintenant !</strong></p>
```

It is tested to be mobile/desktop displayed to announce the current translation and to not change the number of line of each page. That allows us to continue translation with correct line-to-line matching.

Two options:

- To keep this PR and wait for more page to be translated.
  No content « not French » on the online French website will be accessible but already translated part will not be available online too.

- To merge this PR and offer this content to online french people
  That allows already translated page to be accessible and not already translated pages to be joined by people reading the french message « under translation ».

I let you decide but it was a great help for Vuejs-FR to have the website partially translated to let website to be adopted page by page and allows us to tweet the advancement to allows visibility to project.

In the case you keep this PR here a while, she will be updated each time a new page will be translated.

I think all website could be in French on December (maybe November if all continue as currently!).

### CODE REVIEW

**Comment by Atinux** [comment]
Hey @Haeresis 

I will merge it and make it live :)

Could you make a PR to add the French flag on nuxtjs.org repo please?

**Comment by Haeresis** [comment]
I will

**Comment by Atinux** [comment]
In fact, we already have the french flag ahah, it's live!

https://fr.nuxtjs.org/

**Comment by Haeresis** [comment]
👏 We provide the `module` file to complete the full Guide part just right now ;)

**Pull request merged**
