### PR TITLE
[Done] Korean Translation

### PR DESCRIPTION
**Pull request by DiyLecko**
List copied from [#36](https://github.com/nuxt/docs/pull/36) Thanks to [@inouetakuya](https://github.com/inouetakuya)

# Translation progress:

- [x] lang.json

## Guide

- [x] menu.json

### PROLOGUE

- [x] index.md

- [x] contribution-guide.md

### GETTING STARTED

- [x] installation.md
- [x] directory-structure.md
- [x] configuration.md
- [x] routing.md
- [x] views.md
- [x] async-data.md
- [x] assets.md
- [x] plugins.md
- [x] vuex-store.md
- [x] commands.md
- [x] development-tools.md

## API

- [x] menu.json

### PAGES

- [x] index.md

- [x] pages-fetch.md
- [x] pages-head.md
- [x] pages-layout.md
- [x] pages-middleware.md
- [x] pages-scrolltotop.md
- [x] pages-transition.md
- [x] pages-validate.md

### COMPONENTS

- [x] components-nuxt.md
- [x] components-nuxt-child.md
- [x] components-nuxt-link.md

### CONFIGURATION

- [x] configuration-build.md
- [x] configuration-cache.md
- [x] configuration-css.md
- [x] configuration-dev.md
- [x] configuration-env.md
- [x] configuration-generate.md
- [x] configuration-head.md
- [x] configuration-loading.md
- [x] configuration-plugins.md
- [x] configuration-rootdir.md
- [x] configuration-router.md
- [x] configuration-srcdir.md
- [x] configuration-transition.md

### NUXT MODULE

- [x] nuxt-render-and-get-window.md
- [x] nuxt-render-route.md
- [x] nuxt-render.md
- [x] nuxt.md

## Examples

- [x] menu.json

### ESSENTIALS

- [x] hello-world.md
- [x] seo-html-head.md

### CUSTOMIZATION

- [x] cached-components.md
- [x] custom-loading.md
- [x] custom-routes.md
- [x] global-css.md
- [x] layouts.md
- [x] middleware.md
- [x] nested-routes.md
- [x] plugins.md
- [x] routes-transitions.md

### ADVANCED

- [x] async-data.md
- [x] auth-routes.md
- [x] vuex-store.md
- [x] i18n.md
- [x] testing.md

## FAQ

- [x] menu.json

### CONFIGURATION

- [x] external-resources.md
- [x] pre-processors.md
- [x] jsx.md
- [x] postcss-plugins.md
- [x] extend-webpack.md
- [x] webpack-plugins.md
- [x] host-port.md
- [x] google-analytics.md

### DEVELOPMENT

- [x] window-document-undefined.md
- [x] css-flash.md
- [x] async-data-components.md
- [x] duplicated-meta-tags.md

### DEPLOYMENT

- [x] heroku-deployment.md
- [x] now-deployment.md
- [x] surge-deployment.md
- [x] github-pages.md

### CODE REVIEW

**Comment by ChangJoo-Park** [comment]
👍

**Comment by jicjjang** [comment]
👍

**Comment by DiyLecko** [comment]
@alexchopin 
Hello, our korean translation is done.
Please check and merge.
Thank you!

Our Translators:
me,
@jicjjang ,
@wanybae ,
@rellario

**Comment by wanybae** [comment]
- Method: 메서드 vs 메소드 ?

**Comment by jicjjang** [comment]
ㄴ whatever you want

**Pull request merged**
