### PR TITLE
ITALIAN - Nuxtjs Guide traduction

### PR DESCRIPTION
**Pull request by MatthewSaintBull**
Started translating (when is possible for me) Nuxt.js docs in italian.
Only index.md is translated actually.

### CODE REVIEW

**Comment by nigimaster** [comment]
Hi @MatthewSaintBull and @manniL, I am Italian and currently implementing nuxt at work so I really want to help. Is this still possible? Thank you!

**Comment by MatthewSaintBull** [comment]
> Hi @MatthewSaintBull and @manniL, I am Italian and currently implementing nuxt at work so I really want to help. Is this still possible? Thank you!

Hi, Sure! asap I'll start again with the translation :)

**Comment by nigimaster** [comment]
Hi, great! I'll do as well. Best regards!

**Comment by debs-obrien** [comment]
Thanks for your contributions. We are now closing this repo as docs have now moved to nuxtjs.org using content module. Please continue your contributions on that site especially focusing on the guides folder which is the new docs. Thanks

https://github.com/nuxt/nuxtjs.org/blob/master/README.md

**Pull request closed without merging**
