### PR TITLE
nuxt.config.js does not accept import statement

### PR DESCRIPTION
**Pull request by floflock**

### CODE REVIEW

**Comment by manniL** [comment]
Nuxt's config **does support ESM syntax**  🤔 

see https://twitter.com/TheAlexLichter/status/1098607134282006541

**Comment by floflock** [comment]
@manniL should be, but have a look?
image

**Comment by manniL** [comment]
If you use express or another `server.js` this doesn't apply that easily as the "entrypoint" doesn't understand ESM syntax. Use `node -r esm server.js` to apply.

**Comment by floflock** [comment]
@manniL thanks. Guess you mean uncompiled ```server/index.js```.

**Pull request closed without merging**
