### PR TITLE
ja: Fix typo

### PR DESCRIPTION
**Pull request by mtfum**

### CODE REVIEW

**Comment by aytdm** [comment]
@manniL I'm sorry for bothering you, but could you please merge two PR ( this #1477 and #1479 ) when you're available? I and @inouetakuya can not merge the PR for some reason.  ( I ask `@Atinux` 
 to check our access right in [this comment](https://github.com/nuxt/docs/pull/1482#issuecomment-511080945) )

**Comment by manniL** [comment]
Sure @aytdm

**Comment by aytdm** [comment]
@manniL Thank you ☺️

**Comment by Atinux** [comment]
Should be fixed now @aytdm 
Sorry for the delay

**Comment by aytdm** [comment]
@Atinux I appreciate your kind response during your busy time. Let me check it over.

**Pull request merged**
