### PR TITLE
fixed a small grammar issue on asyncData page

### PR DESCRIPTION
**Pull request by briancbarrow**
When reviewing asyncData documentation I found a small grammar error that I fixed here.

### CODE REVIEW

**Comment by Atinux** [comment]
Thanks @briancbarrow but could you remove the changes applied on the code (using `"` and `;`) to keep the same convention we have?

**Comment by briancbarrow** [comment]
Sorry @Atinux and @manniL that it has taken me so long to get to this. So you need me to remove the `"` and `;` ?

**Comment by manniL** [comment]
Yes. Please remove all changes regarding the code examples (double quotes, semicolons, space between fn name and arguments, ...)

**Comment by Atinux** [comment]
Ping before closing 😬

**Pull request closed without merging**
