### PR TITLE
[WIP] Italian Translation (it)

### PR DESCRIPTION
**Pull request by kalidiagne**
# **Translation progress:**

## Guide

**GETTING STARTED**

- [ ]  Introduction
- [ ]  Installation
- [ ]  Directory structure
- [ ]  Configuration
- [ ]  Commands

**ROUTER**

- [ ]  Basic Routes
- [ ]  Dynamic Routes
- [ ]  Nested Routes
- [ ]  Transitions
- [ ]  Middleware

**VIEWS**

- [ ]  Pages
- [ ]  Layouts
- [ ]  Custom Loading
- [ ]  HTML Head

**DATA**

- [ ]  Async data
- [ ]  Vuex store

**RESOURCES**

- [ ]  Assets
- [ ]  Static
- [ ]  Plugins

**DEV TOOLS**

- [ ]  ESLint
- [ ]  Unit Testing

**MISCELLANEOUS**

- [ ]  Contribution Guide
- [ ]  Release Notes

**API**

**NUXT MODULE**

- [ ]  Usage
- [ ]  Render
- [ ]  RenderRoute
- [ ]  RenderAndGetWindow

**CONFIGURATION**

- [ ]  Build
- [ ]  Cache
- [ ]  CSS
- [ ]  Env
- [ ]  Generate
- [ ]  Head
- [ ]  Loading
- [ ]  Plugins
- [ ]  Router

**PAGES**

- [ ]  Context
- [ ] Examples

**ESSENTIALS**

- [ ]  Hello world
- [ ]  SEO HTML Head
- [ ] CUSTOMIZATION

- [ ]  Cached Components
- [ ]  Custom Loading
- [ ]  Custom Routes
- [ ]  Global CSS
- [ ]  Layouts
- [ ]  Plugins
- [ ]  Routes transitions

**ADVANCED**

- [ ]  Async Datas
- [ ]  Auth Routes
- [ ]  Vuex Store
- [ ]  Testing

**FAQ**

- [ ]  External Resources
- [ ]  Heroku Deployment
- [ ]  PostCSS Plugins

### CODE REVIEW

**Comment by Atinux** [comment]
Hi!

Could you wait for the 1.0 to be out before translating please? This way you will be able to use GitLocalize :)

**Comment by KalidouDiagne** [comment]
Hi! @Atinux, Sure! i'm waiting for the release :)

**Comment by Atinux** [comment]
Hi @kalidiagne 

I believe you can start working on it now if you're still motivated :)

**Comment by Atinux** [comment]
Hi @kalidiagne 

It will be faster and easier to use GitLocalize directly: https://gitlocalize.com/repo/100/it

**Pull request closed without merging**
