### PR TITLE
chore(readme/ja): Remove unnecessary description

### PR DESCRIPTION
**Pull request by aytdm**
I updated following two files. PTAL, when you get a chance🙏
+ Readme.md
+ the Japanese translation guide（[Compare revision](https://github.com/vuejs-jp/ja.docs.nuxtjs/wiki/Home/_compare/9ab8cf86787555319f23df47c929c192b610661b...5bc675bf4aa2425c950944c720566efb2ff8c9eb)）

resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/204

### CODE REVIEW

**Comment by aytdm** [comment]
@inouetakuya Thanks! BTW, Do you have authority to merge the PR? ( I lost the authority. ) If yes, I would like to ask someone to merge this PR.

**Comment by aytdm** [comment]
Hi @Atinux,
For some reason I lost write access. Would you add write access to me again if there is no problem?

BTW, I'm looking forward to meeting you in Vue Fes Japan!

**Comment by inouetakuya** [comment]
@aytdm 

Sorry for the late response :pray:

I do NOT have authority to merge this PR, neither. :sweat_smile:

0EA8D969E60CBC3D15AC0895554241FD

---

@Atinux @clarkdo

The build of CircleCI does not seem to work. :thinking:

Could you help us?

**Comment by clarkdo** [comment]
@aytdm @inouetakuya Thanks!

**Pull request merged**
