### PR TITLE
Dynamic transition depending on the context

### PR DESCRIPTION
**Pull request by OlzhasAlexandrov**

### CODE REVIEW

**Comment by Atinux** [comment]
Hi @OlzhasAlexandrov 

Actually, the transition method does not receive the context as a parameter, see https://nuxtjs.org/api/pages-transition

**Comment by Atinux** [comment]
But it may be useful to give it as 3rd argument I think.

**Comment by OlzhasAlexandrov** [comment]
@Atinux Have you tried it? It works:
https://glitch.com/edit/#!/join/7dc4ddfd-5332-4e49-8f3f-c7f08af53c1b

**Comment by Atinux** [comment]
@OlzhasAlexandrov it's not the context but 2 arguments, the page where it's navigating to and the page where he's leaving.

**Pull request closed without merging**
