### PR TITLE
Improve inject documentation

### PR DESCRIPTION
**Pull request by manniL**
related: nuxt/nuxt.js/issues/2233

### CODE REVIEW

**Comment by Atinux** [comment]
Wow thank you so much @manniL

**Comment by manniL** [comment]
No problem @Atinux :relaxed:

**Comment by doriandrn** [comment]
Thanks for this!
In the latest examples, you have used `new` which is a reserved word in JS and using it as a value might be confusing for some people. I would really change it to `newValue` or something similar.

**Comment by manniL** [comment]
@doriandrn Thanks for letting me know! Will fix it up in a minute :relaxed:

**Pull request merged**
