### PR TITLE
en: fixed how to use static assets with url reference

### PR DESCRIPTION
**Pull request by onuriltan**

### CODE REVIEW

**Comment by onuriltan** [comment]
> Could you provide more information?
> 
> The `@` alias should work as well.

I tried `background: url("@assets/banner.svg")` and `background: url("@/assets/banner.svg")`. Both of them didn't work except `background: url("~@/assets/banner.svg")`

**Comment by onuriltan** [comment]
@manniL have you tried it?

**Comment by manniL** [comment]
@onuriltan 

Sorry for the delay. You are right! 
Though I'd say that this is a bug. Maybe @clarkdo or @pi0 know more?

The issue applies to all url paths starting with @.

**Comment by onuriltan** [comment]
@manniL okey then, I will create a issue to vue repo :)

**Comment by manniL** [comment]
@onuriltan It should be a Nuxt issues though, so feel free to open a request through bug.nuxtjs.org ☺️

**Comment by onuriltan** [comment]
@manniL opened [here](https://github.com/nuxt/nuxt.js/issues/6920) on nuxt repo 🙂

**Pull request closed without merging**
