### PR TITLE
Explaining function behaviour in a clearer way

### PR DESCRIPTION
**Pull request by davidemorotti**
Hi, I was struggling at understanding why the fetch function doesn't always load server-side.
Basing on this explanation: https://github.com/nuxt/nuxtjs.org/issues/106#issuecomment-360808831 (who made me understand how nuxtjs works), I decided to try a different way of describing the function, hopefully helping peoples with the same problem.

### CODE REVIEW

**Comment by manniL** [comment]
Thanks a lot @davidemorotti 
It really helps to get insights from people who are learning and experiencing problems 🙏 

I've altered the content a little and merged it 👍

**Comment by davidemorotti** [comment]
Thank you for updating the documentation :)
Hope this will help someone understanding the logic better.

I’ve also seen you published once a schema representing the lifecycle of the app on the documentation of the “asyncData” function, why did you guys remove it?

**Comment by manniL** [comment]
@davidemorotti Do you mean https://nuxtjs.org/guide#schema ?

**Comment by davidemorotti** [comment]
ouch… totally missed it 😅
And it is on the first page of the guide… shame on me, sorry 😂

**Pull request merged**
