### PR TITLE
Fixed #scrollbehavior anchor link.

### PR DESCRIPTION
**Pull request by unr**
Previously linked to #scrollBehavior which was invalid.

### CODE REVIEW

**Comment by unr** [comment]
No problem @farzadso :)

**Comment by manniL** [comment]
@unr Thanks :relaxed: 
Is that problem present in other languages as well?

**Comment by farzadso** [comment]
@manniL Just checked. Yes, It exists in other languages too. I think a global replacement is needed.

**Comment by unr** [comment]
Could alternatively update the page to use #scrollBehavior instead 🤔

**Comment by manniL** [comment]
As you wish :relaxed:

**Comment by unr** [comment]
Hmmm, I was hoping to just make that #scrollBehavior change to make it a simpler fix.

Seems that the anchor tag is being generated, not something I can one-character-fix. :)

**Pull request merged**
